# Generated by Django 5.0.14 on 2026-08-13 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel_max_dimension_mm', models.PositiveIntegerField(default=600)),
                ('parcel_max_weight_kg', models.DecimalField(decimal_places=2, default=25, max_digits=6)),
                ('van_load_safety_factor', models.FloatField(default=0.9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParcelShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=12)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_shipment', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('load_length_mm', models.PositiveIntegerField()),
                ('load_width_mm', models.PositiveIntegerField()),
                ('load_height_mm', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('home_depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vans', to='customers.deliveryaddress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('LOCKED', 'Locked'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('total_distance_km', models.FloatField(blank=True, null=True)),
                ('total_duration_min', models.FloatField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_runs', to=settings.AUTH_USER_MODEL)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='delivery.van')),
            ],
            options={
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('load_position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('driver_notes', models.TextField(blank=True)),
                ('delivery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='delivery.deliveryrun')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='orders.order')),
            ],
            options={
                'ordering': ['delivery_run', 'sequence'],
                'unique_together': {('delivery_run', 'order')},
            },
        ),
    ]
