# Generated by Django 5.0.14 on 2026-08-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('CASH_ON_DELIVERY', 'Cash on delivery'), ('BANK_TRANSFER', 'Bank transfer')], default='CARD', max_length=20),
        ),
    ]
