# Generated by Django 5.0.14 on 2026-08-13 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('DELIVERY_RUN', 'Delivery run'), ('PARCEL_BATCH', 'Parcel batch')], default='DELIVERY_RUN', max_length=15)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete')], default='OPEN', max_length=12)),
                ('delivery_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_list', to='delivery.deliveryrun')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManufacturingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_label', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('finish_name', models.CharField(blank=True, max_length=120)),
                ('colour', models.CharField(blank=True, max_length=60)),
                ('width_mm', models.PositiveIntegerField()),
                ('height_mm', models.PositiveIntegerField()),
                ('depth_mm', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CUTTING', 'Cutting'), ('ASSEMBLY', 'Assembly'), ('FINISHING', 'Finishing'), ('READY', 'Ready')], default='PENDING', max_length=12)),
                ('manufacturing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manufacturing.manufacturinglist')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_items', to='orders.orderitem')),
            ],
            options={
                'ordering': ['manufacturing_list', 'id'],
            },
        ),
    ]
